apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-module-deployment
spec:
  selector:
    matchLabels:
      app: admin-module
  replicas: 2
  template:
    metadata:
      labels:
        app: admin-module
    spec:
      containers:
        - name: admin-module
          image: arfaoui01/adminmodule:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: admin-module-service
spec:
  selector:
    app: admin-module
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
