/**
 * OpenApi specification 
 * OpenApi documentation for Admin Module Demo
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColumnInfo } from './columnInfo';
import { ForeignKey } from './foreignKey';


export interface TableInfo { 
    name?: string;
    type?: string;
    pk?: ColumnInfo;
    totalRows?: number;
    columns?: Array<ColumnInfo>;
    foreignKeys?: Array<ForeignKey>;
}

